ScavengeRUs/Models/Entities/Hunt.cs
using Microsoft.Build.Framework;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScavengeRUs.Models.Entities
{
    /// <summary>
    /// This is the object for a Hunt. If you need to add a column to the user table this is where you do it. 
    /// The database table is built from this. If you change anything here add a new migration and update the database
    /// (in package manager console run "add-migration mig{xx}" "update-database"
    /// </summary>
    public class Hunt
    {
        public int Id { get; set; }
        [DisplayName("Title"), Required]
        public string? HuntName { get; set; }
        [Required]
        public string? Theme { get; set; }
        [DisplayName("Invitation Text"), Required]
        public string? InvitationText { get; set; }
        [DisplayName("Start Date/Time"), Required]
        public DateTime StartDate{ get; set; }
        [DisplayName("End Date/Time"), Required]
        public DateTime EndDate { get; set; }
        [DisplayName("Tasks")]
        public ICollection<HuntLocation> HuntLocations { get; set; } = new List<HuntLocation>();  
        [DisplayName("Access Code")]
        public ICollection<AccessCode>? AccessCodes { get; set; } = new List<AccessCode>();
        public ICollection<ApplicationUser> Players { get; set; } = new List<ApplicationUser>();
    }
}

ScavengeRUs/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScavengeRUs.Data;
using ScavengeRUs.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Routing;
using ScavengeRUs.Services;

namespace ScavengeRUs.Controllers
{
     //makes sure that only admin can see this page
    public class LocationsController : Controller
    {
        private readonly IUserRepository _userRepo;
        private readonly IHuntRepository _huntRepo;
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// This method injects the context into the class so that the methods can connect to
        /// the database
        /// </summary>
        /// <param name="context"></param>
        public LocationsController(ApplicationDbContext context, IHuntRepository huntRepo, IUserRepository userRepo)
        {
            _userRepo = userRepo;
            _huntRepo = huntRepo;
            _context = context;
        }

        /// <summary>
        /// This method maps to the /Locations URL. It shows the table
        /// </summary>
        /// <returns></returns>
        /// 
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
              return View(await _context.Location.ToListAsync());
        }

        /// <summary>
        /// This method shows the details of a specific location based on Id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        /// 
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Location == null)
            {
                return NotFound();
            }

            var location = await _context.Location
                .FirstOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        /// <summary>
        /// This is the page that will be shown when the admin want to create a new location from the 
        /// website
        /// </summary>
        /// <returns></returns>
        /// 
        [Authorize(Roles = "Admin")]
        public IActionResult Create([Bind(Prefix = "Id")] int huntid)
        {
            return View();
        }

        /// <summary>
        /// This method will be called when the admin submits the newly created location
        /// </summary>
        /// <param name="location"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind(Prefix = "Id")] int huntid, Location location)
        {
            if (ModelState.IsValid)
            {
                _context.Add(location);
                await _context.SaveChangesAsync();
                if (huntid != 0)
                {
                    return RedirectToAction("ManageTasks", "Hunt", new { id = huntid });
                }
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        /// <summary>
        /// This is the page that will be shown when the admin attempts to edit a location
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        /// 
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Location == null)
            {
                return NotFound();
            }

            var location = await _context.Location.FindAsync(id);
            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }

        /// <summary>
        /// This method will be called when the admin submits the edit to the location from the previous
        /// method
        /// </summary>
        /// <param name="id"></param>
        /// <param name="location"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,HuntId,Place,Lat,Lon,Task,AccessCode,QRCode,Answer")] Location location)
        {
            if (id != location.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(location);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationExists(location.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        /// <summary>
        /// This page will be shown when the admin attempts to delete a location from the site
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        /// 
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Location == null)
            {
                return NotFound();
            }

            var location = await _context.Location
                .FirstOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        /// <summary>
        /// This method will activate when the admin submits the delete action on a location
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Location == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Location'  is null.");
            }
            var location = await _context.Location.FindAsync(id);
            if (location != null)
            {
                _context.Location.Remove(location);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// This method checks to make sure that a Location row exists in the database
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool LocationExists(int id)
        {
          return _context.Location.Any(e => e.Id == id);
        }
        /// <summary>
        /// This method validates an answer for a task. Used by an AJAX call from the hunt page. See site.js
        /// </summary>
        /// <param name="id"></param>
        /// <param name="taskid"></param>
        /// <param name="answer"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin, Player")]
        public async Task<IActionResult> ValidateAnswer([FromForm]int id, int taskid, string answer)
        {
            var currentUser = await _userRepo.ReadAsync(User.Identity?.Name!);                              //gets current user
            var location = await _context.Location.FirstOrDefaultAsync(m => m.Id == taskid);                //gets the task
            if (answer != null && answer.Equals(location?.Answer, StringComparison.OrdinalIgnoreCase))      //check is answer matches
            {
                currentUser?.TasksCompleted!.Add(location); //Update the players completed tasks
                await _context.SaveChangesAsync();          
                return Json(new { success = true});
            }
            return Json(new { success = false });
        }
    }
}

ScavengeRUs/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ScavengeRUs.Models.Entities;
using ScavengeRUs.Services;
using System;
using System.Security.Claims;

namespace ScavengeRUs.Controllers
{

    /// <summary>
    /// Anything in this controller (www.localhost.com/users) can only be viewed by Admin
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepo;
        string defaultPassword = "Etsupass12!";
        /// <summary>
        /// This is the dependecy injection for the User Repository that connects to the database
        /// </summary>
        /// <param name="userRepo"></param>
        public UserController(IUserRepository userRepo)
        {
            _userRepo = userRepo;
        }
        /// <summary>
        /// This is the landing page for www.localhost.com/user/manage aka "Admin Portal"
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Manage(string searchString)
        {
            var users = await _userRepo.ReadAllAsync(); //Reads all the users in the db

            //if the admin didn't search for anything just return all the users
            if(string.IsNullOrEmpty(searchString))
                return View(users);  //Right click and go to view to see HTML

            //this line of code filters out all the users whose emails and phone numbers do not
            //contain the search string
            var searchResults = users.Where(user => user.Email.Contains(searchString) 
            || !string.IsNullOrEmpty(user.PhoneNumber) && user.PhoneNumber.Contains(searchString));

            return View(searchResults);
        }
        /// <summary>
        /// This is the HtmlGet landing page for editing a User
        /// </summary>
        /// <param name="username"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit([Bind(Prefix = "id")]string username)
        {
            var user = await _userRepo.ReadAsync(username);
            return View(user);
        }
        /// <summary>
        /// This is the method that executes when hitting the submit button on a edit user form.
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Edit(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                await _userRepo.UpdateAsync(user.Id, user);
                return RedirectToAction("Manage");
            }
            return View(user);
        }
        /// <summary>
        /// This is the landing page to delete a user aka "Are you sure you want to delete user X?"
        /// </summary>
        /// <param name="username"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete([Bind(Prefix ="id")]string username)
        {
            var user = await _userRepo.ReadAsync(username);
            if (user == null)
            {
                return RedirectToAction("Manage");
            }
            return View(user);
        }
        /// <summary>
        /// This is the method that gets executed with hitting submit on deleteing a user
        /// </summary>
        /// <param name="username"></param>
        /// <returns></returns>
        /// 
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed([Bind(Prefix = "id")]string username)
        {
            await _userRepo.DeleteAsync(username);
            return RedirectToAction("Manage");
        }
        /// <summary>
        /// This is the landing page for viewing the details of a user (www.localhost.com/user/details/{username}
        /// </summary>
        /// <param name="username"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details([Bind(Prefix = "id")]string username)
        {
            var user = await _userRepo.ReadAsync(username);

            return View(user);
        }
        /// <summary>
        /// This is the landing page to create a new user from the admin portal
        /// </summary>
        /// <returns></returns>

        public IActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// This is the method that is executed when hitting submit on creating a user
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Create(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                user.UserName = user.Email;
                await _userRepo.CreateAsync(user, defaultPassword);
                return RedirectToAction("Details", new { id = user.UserName });
            }
            return View(user);
            
        }
        /// <summary>
        /// This is the profile page for a user /user/profile/
        /// </summary>
        /// <param></param>
        /// <returns></returns>
        public async Task<IActionResult> Profile()
        {
            var currentUser = await _userRepo.ReadAsync(User.Identity?.Name!);
            return View(currentUser);
        }
    }
}

ScavengeRUs/Views/Hunt/AddPlayerToHunt.cshtml
@model ScavengeRUs.Models.Entities.ApplicationUser
@{
    ViewData["Title"] = "Add Player";
    var hunt = (Hunt)ViewData["Hunt"];
}
<h1>Add player to @hunt.HuntName</h1>
<h5>*will create user if not registered</h5>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPlayerToHunt">
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" required class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" required class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" required class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" required class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccessCode!.Code" class="control-label"></label>
                <input readonly placeholder="{PhoneNumber}/{HuntName}" asp-for="AccessCode!.Code" class="form-control" />
                <span asp-validation-for="AccessCode!.Code" class="text-danger"></span>
            </div>
            <div class="form-group">
      @*          <p style="margin-top:5px">*Default password is Etsupass12!</p>*@
                <input type="submit" value="Add" class="btn btn-primary mt-3" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="ViewPlayers" asp-route-id="@hunt.Id">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

ScavengeRUs/Views/Hunt/AddTasks.cshtml
@model IEnumerable<ScavengeRUs.Models.Entities.Location>

@{
    var hunt = (Hunt?)ViewData["Hunt"];
    ViewData["Title"] = "Add Tasks to Hunt";
}

<h1>Add Tasks of @hunt.HuntName</h1>

<p>
    <a asp-action="ViewTasks" asp-route-Id="0" asp-route-huntid="@hunt.Id" style="padding-left: 3px">Back to Hunt</a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Task)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Place)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Task)
                </td>
                <td>
                    @Html.ActionLink("Add", "AddTask", new {  id=item.Id,huntid=hunt.Id  })
                </td>
                <td>
                </td>
            </tr>
        }
    </tbody>
</table>

ScavengeRUs/Views/Hunt/Create.cshtml
@model ScavengeRUs.Models.Entities.Hunt

@{
    ViewData["Title"] = "Create Hunt";
}
<h1>Create a new Hunt</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             <div class="form-group">
                <label asp-for="HuntName" class="control-label"></label>
                <input asp-for="HuntName" required class="form-control" />
                <span asp-validation-for="HuntName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" required class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" required class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvitationText" class="control-label"></label>
                <input asp-for="InvitationText" required class="form-control" />
                <span asp-validation-for="InvitationText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Theme" class="control-label"></label>
                <input asp-for="Theme" required class="form-control" />
                <span asp-validation-for="Theme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create Hunt" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ScavengeRUs/Views/Hunt/Delete.cshtml
@model ScavengeRUs.Models.Entities.Hunt

@{
    ViewData["Title"] = "Delete";
}

<h2>Are you sure you want to delete @Model.HuntName?</h2>
<div>
    <hr />
    <dl class="row">
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HuntName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HuntName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ScavengeRUs/Views/Hunt/Index.cshtml
@model IEnumerable<ScavengeRUs.Models.Entities.Hunt>

@{
    ViewData["Title"] = "Hunts";
}

<h1>Displaying all hunts</h1>

<p>
    <a asp-action="Create" style="padding-right: 3px">Create New Hunt</a> |
    <a asp-controller="locations" asp-action="Index" style="padding-right: 3px">Manage All Tasks</a> |
    <a asp-controller="User" asp-action="Manage" style="padding-left: 3px">Back to Admin Portal</a>
</p>
<table class="table">
    <thead>
        <tr>
@*            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.HuntName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                Time Remaining
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Players)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HuntLocations)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
@*            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>  *@          
            <td>
                @Html.DisplayFor(modelItem => item.HuntName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                    @{
                        var timeRemaining = (item.EndDate - DateTime.Now).ToString();
                        if (TimeSpan.Parse(timeRemaining).Seconds<0)
                        {
                            timeRemaining = "Ended";
                        }
                        else
                        {
                            timeRemaining = timeRemaining.Substring(0, timeRemaining.LastIndexOf("."));
                        }
                }
                    @Html.DisplayFor(modelItem => timeRemaining)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Players.Count)
             </td>
            <td>
                @Html.DisplayFor(modelItem => item.HuntLocations.Count)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |*@
                @Html.ActionLink("View Hunt", "ViewTasks", new {  id=item.Id  }) |
                @Html.ActionLink("Delete Hunt", "Delete", new {  id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>

ScavengeRUs/Views/Hunt/ManageTasks.cshtml
@model IEnumerable<ScavengeRUs.Models.Entities.Location>

@{
    var hunt = (Hunt?)ViewData["Hunt"];
    ViewData["Title"] = "Add Tasks to Hunt";
}

<h1>Add Tasks of @hunt.HuntName</h1>

<p>
    <a asp-controller="Locations" asp-action="Create" asp-route-Id="@hunt.Id" style="padding-left: 3px">Create new task</a> |
    <a asp-action="ViewTasks" asp-route-Id="@hunt.Id" style="padding-left: 3px">Back to Hunt</a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Task)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Place)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Task)
                </td>
                <td>
                    @{
                        var locationCheck = hunt.HuntLocations.FirstOrDefault(a => a.LocationId == item.Id);
                    }
                    @if(locationCheck != null){
                        @Html.ActionLink("Remove", "RemoveTask", new { id=item.Id,huntid=hunt.Id  }, new { @style = "color:red;"})
                    }
                    else{
                        @Html.ActionLink("Add", "AddTask", new { id=item.Id,huntid=hunt.Id  })
                    }

                </td>
                <td>
                </td>
            </tr>
        }
    </tbody>
</table>

ScavengeRUs/Views/Hunt/RemoveUser.cshtml
@model ScavengeRUs.Models.Entities.ApplicationUser

@{
    ViewData["Title"] = "Delete";
}



<h3>Are you sure you want to remove this user from this hunt?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    <form asp-action="RemoveUserConfirmed">
        <input type="submit" value="Remove" class="btn btn-danger" /> |
        <input type="hidden" name="username" value="@Model.UserName"  />
        <input type="hidden" name="huntId" value="@ViewData["Hunt"]" />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ScavengeRUs/Views/Hunt/ViewPlayers.cshtml
@model IEnumerable<ScavengeRUs.Models.Entities.ApplicationUser>

@{
    var hunt = (Hunt?)ViewData["Hunt"];
    ViewData["Title"] = "View Players of hunt";
}

<h1>Active Users of @hunt.HuntName</h1>

<p>
    <a asp-action="ViewTasks" asp-route-Id="@hunt.Id" style="padding-left: 3px">Back to hunt</a> |
    <a asp-action="AddPlayerToHunt" asp-route-Id="@hunt.Id" style="padding-right: 3px">Add a user to this Hunt</a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccessCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (!Model.Any())
        {
            <tr>
                <td>
                    <span> No players are assigned to this hunt</span>
                </td>
                <td>
                </td>                
                <td>
                </td>                
                <td>
                </td>                
                <td>
                </td>
            </tr>
        }

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(model => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(model => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(model => item.AccessCode.Code)
                </td>
                <td>
                    @Html.ActionLink("Revoke Access", "RemoveUser", new { id=item.UserName, huntId=hunt.Id })
                </td>
            </tr>
        }
    </tbody>
</table>